name: nijhanand
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.8.4
  firebase_core: ^2.15.0
  get: ^4.6.5
  firebase_auth: ^4.7.2
  rename: ^2.0.1
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Rasa
      fonts:
        - asset: assets/fonts/Rasa.ttf
    - family: Noto Serif Gujarati
      fonts:
        - asset: assets/fonts/NotoSerifGujarati-Regular.ttf
    - family: Koninoor Gujarati
      fonts:
        - asset: assets/fonts/Koninoor Gujarati.ttf

